### ISSUE TITLE
How to treat unconventional element symbols? Follow-up to #16

### ISSUE THREAD

**Issue by jmaglic** [jmaglic/MoloVol#17]
Apart from the standard 118 element symbols, what other cases can we expect to encounter, and how should they be treated?

From what I understand, certain automatically created input files will mark ions explicitly, for instance "Pd2+". One proposed solution is to remove any characters after "Pd". However, this would make it very tedious to differentiate between "Pd" and "Pd2+" if the user chooses to do so. I think there are better ways to deal with that, e.g., by only handling this after the calculation has been started, rather than upon import of the inputfile. This would allow the user to specify how to deal with this case.

Apart from this, what other unconventional cases could be expected? Can we expect an inputfile to contain "element symbols" that have a numerical character in the middle? Are molecules ever treated like atoms?

**Comment by rlavendomme** [comment]
Depending on the input file, there are many possible cases.
If we limit ourselves to xyz and pdb, we can still have different cases because xyz files could be generated from crystal structure files where the label of the atom is used instead of the element of the atom (these are two different values).
For example, it is not uncommon to have letters used in the label of C atoms in proteins because there are so many C atoms and there is a limited number of characters allowed for the label (let's say 4 characters), that they need to use letters and numbers to differentiate each carbon atom in the structure.

As an example of how different elements are handled by a reputable software (Mercury from the CCDC), the following xyz file containing wrong elements on purpose still recognize many of them.
```Pd2+ 0 0 0
Pd 3 0 0
Pd4- 5 0 0
PD 7 0 0
PDD 9 0 0
Can 11 0 0
D 13 0 0
Dz 15 0 0
Kz 17 0 0
Fz 19 0 0
C2A 21 0 0
C+5 23 0 0
C+a 25 0 0
2C 27 0 0
2+C 29 0 0
+C 31 0 0```
![image](https://user-images.githubusercontent.com/65511614/90027993-6fbded80-dcb9-11ea-8d83-c13bdaa554e1.png)

In my opinion, it is better and more convenient for a user lambda if elements are recognized by their symbol without considering characters following the first occurrence of any non alphabetic character.

In the above example, we don't want the present program to list C+5, C+a, C2A as different elements. All of them should be listed as C. Otherwise, in a crystal structure of protein, there could be thousands of "different elements" listed by the software.

Even stronger case, the program could recognize only the first two alphabetic characters since, in a pdb file, only two characters are allowed for element symbols (characters 77 and 78 in an ATOM or HETATM line, see http://www.wwpdb.org/documentation/file-format ).

Yet I would still prefer to allow for longer strings of letters to be accepted for xyz files to allow users to define conveniently different type of elements (such as differentiation Pd and Pd2+ as Pd and Pdion, for example). Indeed, if there are only 2 characters allowed and registered, a user would need to be creative to define recognizable custom symbols and check that symbols don't already exist (I suppose that most chemists don't know all 118 element symbols by heart, some elements being very rarely used).

**Comment by jmaglic** [comment]
What about "2C", "2+C", and "+C" in your above example? It would be fairly easy to strip all non-letter characters, and evaluate all of these as "C". Is there is need for that? Do you believe we can expect to encounter these examples?

**Comment by rlavendomme** [comment]
> What about "2C", "2+C", and "+C" in your above example?
I made these up for testing purpose (to see how they are handled by Mercury) but I don't see how such strings could end up in a chemical structure file and I don't expect any chemist to purposely name elements in a structure file starting with random characters unrelated to the symbol.
I could be wrong. We need to seek opinions of chemists with different backgrounds than ours.

**Comment by jmaglic** [comment]
So to sum up we should:
- Require the first character to be a letter, otherwise ignore the import.
- Convert the first character to uppercase in order not to distinguish between, for instance, "C" and "c".
- Convert all subsequent letters to lowercase in order not to distinguish between, for instance, "Ca" and "CA"
- Only consider characters up to a non-letter character in order not to distinguish between, for instance, "Pd" and "Pd2+" (this could potentially be an import option)
- Allow any number of letter characters as valid symbols as to allow the user to make a custom case, for instance, "Pdion" for "Pd2+"
Are these all cases?

**Comment by rlavendomme** [comment]
> Are these all cases?

I think so (at least for XMol .xyz files).
For PDB files, the format is so rigid that there will be only 2 characters for the symbol anyway.

**Comment by jmaglic** [comment]
I have made a branch to address the issues raised here. The function `strToValidSymbol()` is now used to convert any string to a valid element symbol according to the rules I summed up above. The function is currently only usable inside mode_filereading.cpp, but if it's required elsewhere we could consider moving it or making it a method of the Model class.
