### ISSUE TITLE
Issues with output files

### ISSUE THREAD

**Issue by jmaglic** [jmaglic/MoloVol#55]
### Current status

Each time a calculation concludes, a new output folder is created with a new output file inside.

### Issue

* The user is not asked about saving the output file. Any user that is not aware of the app saving in the background will amass hundreds of folders that are essentially rubbish.
* The app should never write anything to disk without the users consent.
* The fact that all output files are in separate folders makes processing them an immense pain.
* The naming of the output files makes finding specific calculations tedious.
* model_outputfile.cpp is very difficult to read IMO. The Model class should not have authority on where to save files. This should be governed by the Controller.

### Proposed change

* Saving files should be done after the user has specified their intent to save them. The user should specify the output folder.
* All saved files should be placed in the same folder. Their names should contain identifying information about the calculation, and rather than differentiating them by time, they should be differentiated by something else, such as a consecutive number.
* generateReport() should be more self contained. It should take arguments when called by the Controller rather than call global variables. The use of global variables (members of Model) should be avoided at all cost.

### Improvement

* Avoid clutter on the user's disk.
* Align with the design of comparable apps.
* Make code more readable.

**Comment by rlavendomme** [comment]
I agree with most points. I simply prepared a base for output that would be improved later when we are done with calculating functions.

The only point that I would keep it the use of the creation time in some form because it simplifies the classification by alphabetical order without having to keep track or checking all existing files in the output folder.

For example:
In the GUI, tick a box to save output => specify the output folder.
In the output folder, make a folder with the name of the structure file followed by the time (can be as a number like 20210103131705 instead of 2021-01-03_13h17m05s). This is a form that looks unnecessary long but is quite common in output files from analytical equipment in chemistry (e.g. mass spectrometers).
In this folder, save all output files that are requested by the user (report, analyzed structure, surface maps). The analyzed structure output file is useful in case the user excludes some elements or requests the unit cell analysis => it won't be the same as the input file.

We can deactivate the report writing altogether for the moment and deal with that later in my opinion.
