### ISSUE TITLE
Convert volumes and surface areas from nanoscale to macroscale

### ISSUE THREAD

**Issue by rlavendomme** [jmaglic/MoloVol#90]
### Current status

As of now, the volume and surface area values are given for single molecules or unit cells.

### Issue

It is simple but not straightforward to compare data calculated with MoloVol on the nanoscale and values measured on the macroscale.

### Proposed change

Add volume and surface area values per gram in the report file.
For this, the molecular weight needs to be known so the element radii file needs to be updated with elements weight.
The radii file should be renamed elements (or elements_properties).
Then the following formulas can be applied:
```
V [cm^3/g] = V [Å^3] * Navogadro [mol^-1] * 10^-24 [cm^3/Å^3] / M [g/mol]
S [m^2/g] = S [Å^2] * Navogadro [mol^-1] * 10^-20 [m^2/Å^2] / M [g/mol]
```

### Improvement

It could prove useful to get volume and surface area per gram of material, especially to compare to experimental data (e.g. gas sorption for porous solids).

**Comment by jmaglic** [comment]
Changes required off the top of my head:
* Changing the name of the resource file, will require all explicit references in the code to be changed. This is a good opportunity to centralise access to this file, for instance, by creating a function that returns the correct path. This would have the benefit that if we needed to change the name again for whatever reason, then we would only need to change it once.
* Since we're still in pre-release, it's still no issue changing the corresponding command line option for what is currently the radius file ("-fr"). We could change it to something like "-fe"
* In the GUI we should change the text box before the element file path to something like "Element data:"

Should this also be an output in the GUI or should this be limited to the result file? I wouldn't want to risk including clutter to the GUI, but if it makes sense, then it should of course be included in the GUI. Maybe there could be a switch to change values back and forth?

I prefer the name "elements.txt".

**Comment by rlavendomme** [comment]
> Should this also be an output in the GUI or should this be limited to the result file?

I don't think this information is required in the GUI which summarizes the main results without further processing. The report file is there to give detailed results.

I'll open a branch for that feature once I find a reliable consistent source for all elements' molar mass.

**Comment by jmaglic** [comment]
Alright. Please make sure you use getResourcesDir() in misc.cpp to access the directory in which the elements.txt file is located. It may be good to add another function directly inside misc.cpp that's called something like "getElementFilePath()".

I suggest creating a std::map inside the model class, with which to look up mass using the element symbol as key.
